/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=operations-monitor.wrangler.jsonc --include-runtime=false --strict-vars=false --env-interface=OperationsMonitorEnv scripts/operations-monitor-env.d.ts` (hash: 1ef542cef69702e2acd0ec9e4634e8fb)
interface __BaseEnv_OperationsMonitorEnv {
  MONITOR_STATE: KVNamespace;
  BACKUPS_BUCKET: R2Bucket;
  EMAIL: SendEmail;
  CLOUDFLARE_ACCOUNT_ID: string;
  HEALTH_URL: string;
  OPERATIONAL_ALERT_FROM: string;
  OPERATIONAL_ALERT_DRY_RUN: string;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./operations-monitor-worker');
  }
  interface Env extends __BaseEnv_OperationsMonitorEnv {}
}
interface OperationsMonitorEnv extends __BaseEnv_OperationsMonitorEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | 'CLOUDFLARE_ACCOUNT_ID'
      | 'HEALTH_URL'
      | 'OPERATIONAL_ALERT_FROM'
      | 'OPERATIONAL_ALERT_DRY_RUN'
    >
  > {}
}
